# Generated by Django 2.2.5 on 2021-05-03 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('0e79f8ec-abce-11eb-8640-e23649546827'), editable=False),
        ),
    ]
