# Generated by Django 2.2.5 on 2021-05-02 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('0c5112f5-ab7e-11eb-a106-7824afca968b'), editable=False),
        ),
    ]
