# Generated by Django 2.2.5 on 2021-05-03 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('4f0e519a-ac48-11eb-a2bb-7824afca968b'), editable=False),
        ),
    ]
