# Generated by Django 2.2.5 on 2021-05-02 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clerk',
            options={'permissions': [('add_balance', 'can add balance')]},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AddField(
            model_name='clerk',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clerk',
            name='saved_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('a12eafca-ab2b-11eb-96d9-207918e81943'), editable=False),
        ),
        migrations.CreateModel(
            name='TabooList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('addBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Clerk')),
            ],
        ),
    ]
