# Generated by Django 2.2.5 on 2021-05-03 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0002_auto_20210503_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('5f770716-ac48-11eb-b0d6-7824afca968b'), editable=False),
        ),
    ]
