# Generated by Django 2.2.5 on 2021-05-02 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0003_auto_20210502_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('ffe17915-ab94-11eb-b379-7824afca968b'), editable=False),
        ),
    ]
