# Generated by Django 2.2.5 on 2021-04-30 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0004_discussion_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
        migrations.AddField(
            model_name='forum',
            name='customer_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
