# Generated by Django 2.2.5 on 2021-05-03 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0004_auto_20210502_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerk',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='clerk',
            name='saved_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('3a0f4f85-abb2-11eb-93c6-7824afca968b'), editable=False),
        ),
    ]
