# Generated by Django 2.2.5 on 2021-05-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0004_auto_20210502_1823'),
        ('onlineComputerStore', '0002_auto_20210503_0111'),
    ]

    operations = [
    ]
