# Generated by Django 2.2.5 on 2021-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0005_auto_20210430_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='default_img/400x650.png', upload_to='item_img/'),
        ),
    ]
