# Generated by Django 2.2.5 on 2021-05-03 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0005_merge_20210503_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('d65d54d5-abcf-11eb-8050-e23649546827'), editable=False),
        ),
    ]
