# Generated by Django 2.2.5 on 2021-05-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0003_auto_20210503_1547'),
        ('onlineComputerStore', '0005_auto_20210502_2152'),
    ]

    operations = [
    ]
