# Generated by Django 2.2.5 on 2021-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0006_auto_20210430_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='default_img/400x650.png', null=True, upload_to='item_img/'),
        ),
    ]
