# Generated by Django 2.2.5 on 2021-04-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0006_auto_20210429_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='discussion',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
