# Generated by Django 2.2.5 on 2021-04-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0007_auto_20210430_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
