# Generated by Django 2.2.5 on 2021-05-03 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0007_auto_20210503_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('3cf065d4-abd2-11eb-9c18-e23649546827'), editable=False),
        ),
    ]
