# Generated by Django 2.2.5 on 2021-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0007_auto_20210430_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='img/default_img/400x650.png', null=True, upload_to='img/item_img/'),
        ),
    ]
