# Generated by Django 2.2.5 on 2021-05-01 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0008_auto_20210430_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6c5930c2-8cee-4db9-9587-8e5e7a98ddc7'), editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='url_slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
