# Generated by Django 2.2.5 on 2021-05-03 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0008_auto_20210503_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('04fdb290-abd3-11eb-bfb9-e23649546827'), editable=False),
        ),
    ]
