# Generated by Django 2.2.5 on 2021-05-01 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineComputerStore', '0009_auto_20210430_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='item',
            name='uid',
        ),
        migrations.AddField(
            model_name='customer',
            name='saved_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
