# Generated by Django 2.2.5 on 2021-05-03 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0009_auto_20210503_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('f1c7afd2-abe0-11eb-969d-e23649546827'), editable=False),
        ),
    ]
