# Generated by Django 2.2.5 on 2021-04-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0009_auto_20210430_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
