# Generated by Django 2.2.5 on 2021-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0010_auto_20210501_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='cpu_id',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='gpu_id',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='memory_id',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='core_name',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='category',
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='gpu_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='memory_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='architecture',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='frequency',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='num_cores',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='chipset',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='core_clock',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='num_cuda_cores',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='capacity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
