# Generated by Django 2.2.5 on 2021-05-03 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0010_auto_20210503_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidfor',
            old_name='deli_company',
            new_name='delivery_company',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.UUID('9e3254d3-abe1-11eb-99c9-e23649546827'), editable=False),
        ),
    ]
