# Generated by Django 2.2.5 on 2021-05-01 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineComputerStore', '0013_auto_20210430_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='customer',
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
