# Generated by Django 2.2.5 on 2021-05-01 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0016_auto_20210430_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='url_slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
