# Generated by Django 2.2.5 on 2021-05-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0018_auto_20210501_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumwarning',
            name='discuss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Discussion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
