# Generated by Django 2.2.5 on 2021-05-01 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineComputerStore', '0020_auto_20210501_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumwarning',
            name='report_user',
        ),
        migrations.AddField(
            model_name='forumwarning',
            name='reporter',
            field=models.ForeignKey(default=9, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
        migrations.AlterField(
            model_name='forumwarning',
            name='discuss',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Discussion'),
        ),
    ]
