# Generated by Django 2.2.5 on 2021-05-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0021_auto_20210501_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
