# Generated by Django 2.2.5 on 2021-05-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0023_auto_20210501_0234'),
        ('onlineComputerStore', '0010_auto_20210501_1510'),
    ]

    operations = [
    ]
