# Generated by Django 2.2.5 on 2021-05-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0024_merge_20210501_1542'),
        ('onlineComputerStore', '0011_auto_20210501_1605'),
    ]

    operations = [
    ]
