# Generated by Django 2.2.5 on 2021-05-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0026_auto_20210501_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
        migrations.CreateModel(
            name='TabooList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('addBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Clerk')),
            ],
        ),
    ]
