# Generated by Django 2.2.5 on 2021-05-02 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0027_auto_20210502_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={},
        ),
        migrations.AlterModelManagers(
            name='deliverycompany',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
