# Generated by Django 2.2.5 on 2021-05-02 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0029_auto_20210501_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
        migrations.AlterField(
            model_name='taboolist',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
