# Generated by Django 2.2.5 on 2021-05-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineComputerStore', '0031_auto_20210502_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clerk',
            options={'permissions': [('add_balance', 'can add balance')]},
        ),
        migrations.AddField(
            model_name='clerk',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clerk',
            name='saved_address',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineComputerStore.Forum'),
        ),
    ]
